version: '3'

services:
  broadcast:
    build: broadcast
    ports:
      - 12345:12345
    env_file: .env
    networks:
      - mynetwork
  service1:
    build: node
    ports:
      - 50051:50051
    env_file: .env
    environment:
      - CONFIG_PREFIX=S1
    networks:
      - mynetwork
    depends_on:
      - broadcast
  service2:
    build: node
    ports:
      - 50052:50052
    env_file: .env
    environment:
      - CONFIG_PREFIX=S2
    networks:
      - mynetwork
    depends_on:
      - broadcast
  service3:
    build: node
    ports:
      - 50053:50053
    env_file: .env
    environment:
      - CONFIG_PREFIX=S3
    networks:
      - mynetwork
    depends_on:
      - broadcast
  service4:
    build: node
    ports:
      - 50054:50054
    env_file: .env
    environment:
      - CONFIG_PREFIX=S4
    networks:
      - mynetwork
    depends_on:
      - broadcast
  service5:
    build: node
    ports:
      - 50055:50055
    env_file: .env
    environment:
      - CONFIG_PREFIX=S5
    networks:
      - mynetwork
    depends_on:
      - broadcast

networks:
  mynetwork:
    driver: bridge